import sys
import os
import json
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor

# pyrefly: ignore [missing-import]
from sqlalchemy import create_engine
# pyrefly: ignore [missing-import]
from sqlalchemy.orm import sessionmaker
from app.models import Project, PipelineSession, ToolRun, LogEntry, Artifact

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./faws.db")
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def generate_report(project_id: int):
    db = SessionLocal()
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        print(f"Project {project_id} not found.")
        sys.exit(1)

    session = db.query(PipelineSession).filter(PipelineSession.project_id == project_id).first()
    if not session:
        print(f"No session found for project {project_id}.")
        sys.exit(1)

    filename = f"FAWS_Report_{project_id}.pdf"
    os.makedirs("data/artifacts", exist_ok=True)
    filepath = os.path.join("data/artifacts", filename)

    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        alignment=TA_CENTER,
        textColor=HexColor('#000000')
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=12,
        textColor=HexColor('#2563eb')
    )
    
    body_style = styles["Normal"]

    story = []

    # Title
    story.append(Paragraph(f"Firmware Analysis Report", title_style))
    story.append(Paragraph(f"Project: {project.name}", body_style))
    story.append(Paragraph(f"Architecture: {project.target_architecture}", body_style))
    story.append(Paragraph(f"File Size: {project.file_size} bytes", body_style))
    story.append(Paragraph(f"SHA256: {project.checksum}", body_style))
    story.append(Spacer(1, 20))

    # Executive Summary
    story.append(Paragraph("Executive Summary", heading_style))
    story.append(Paragraph("This report was automatically generated by the FAWS system. It contains the results of a multi-stage static, dynamic, and symbolic firmware analysis.", body_style))
    story.append(Spacer(1, 20))

    # Extracted Tool Data
    story.append(Paragraph("Analysis Stages", heading_style))
    
    tool_runs = db.query(ToolRun).filter(ToolRun.session_id == session.id).order_by(ToolRun.id).all()
    
    for run in tool_runs:
        story.append(Paragraph(f"Tool: <b>{run.tool_name.upper()}</b>", styles["Heading3"]))
        status = "SUCCESS" if run.exit_code == 0 else ("SKIPPED/FAILED" if run.exit_code is not None else "RUNNING")
        story.append(Paragraph(f"Status: {status} | Command: {run.command_executed}", body_style))
        
        # Get important logs
        logs = db.query(LogEntry).filter(
            LogEntry.tool_run_id == run.id,
            LogEntry.log_type == "STDOUT"
        ).limit(10).all()
        
        if logs:
            story.append(Spacer(1, 10))
            for log in logs:
                # Basic escaping
                text = log.message.replace('<', '&lt;').replace('>', '&gt;')
                story.append(Paragraph(f"<font name='Courier' size=8>{text}</font>", body_style))
        
        story.append(Spacer(1, 15))

    doc.build(story)
    
    # Save Artifact in DB
    artifact = Artifact(
        project_id=project_id,
        file_name=filename,
        stage_generated="Report Generation",
        mime_type="application/pdf",
        file_size=os.path.getsize(filepath),
        local_storage_path=filepath
    )
    db.add(artifact)
    db.commit()

    print(f"Generated PDF report at {filepath}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python report_generator.py <project_id>")
        sys.exit(1)
    
    generate_report(int(sys.argv[1]))
